function Insert_In_OBS_Database(conn, id, satelliteId, stationId, epoch, datum)
    global fileID

    Din = dbarray.pack(datum,conn); % Pack it for the given database 
    
    timestamp = sprintf('%04d-%02d-%02d %02d:%02d:%02d.00',...
        epoch(1), epoch(2), epoch(3), epoch(4), epoch(5), epoch(6));
    %fastinsert(conn, 'observation', ...
    %    {'id', 'satelliteid', 'stationid', 'epoch', 'pdist'},...
    %     {id,   satelliteId,   stationId, timestamp, Din});
    
    dinStr = Din.toString();
    
     textVal = ['INSERT INTO observation (id, satelliteid, stationid, epoch, pdist) VALUES (' ...
         mat2str(id)          ', ' ...
         mat2str(satelliteId) ', ' ...
         mat2str(stationId)   ', ' ...
         '''' timestamp ''''  ', ' ...
         '''' char(dinStr) ''''    ...
         ');']; 
     fprintf(fileID,'%s\n',textVal);
end